version: '2.1'
services:
  bamboo:
    image: docker.labnoratory.com/bamboo
    build:
      context: .
    volumes:
      - ./volume:/var/atlassian/bamboo
    environment:
      - DOCKER_HOST=http://172.17.0.1:2376
    ports:
      - 8085:8085
