version: '2.1'
services:
  bamboo:
    image: docker.labnoratory.com/bamboo
    build:
      context: .
    volumes:
      - /var/atlassian/bamboo:/var/atlassian/bamboo
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8085:8085
